type Action {
  id: ID!
  desc: String!
  time: String!
  hero: Hero!
}

input ActionInput {
  heroId: ID!
  desc: String!
  time: String!
}

extend type Mutation {
  addAction(action: ActionInput!): Action
}
